lanl/ports-of-call

- spack-repo/packages/ports-of-call/package.py
Update Spack package for `ports-of-call`to the one now present in Spack upstream
> Sync spackage with spack upstream version

- ports-of-callConfig.cmake.in
If used as in-tree as a submodule downstream, cmake will `include()` a file generated by `export()`, which generates an error (see https://cmake.org/cmake/help/v3.17/policy/CMP0024.html). This includes a guard against invoking the `include()` in the scenario when `ports-of-call` is not the main project. 
This fixes an issue encountered when `singularity-eos` cmake configuration was re-run after the initial cmake generate step. In this case, importing `spiner` submodule would use the prior `export()`-ed `ports-of-callConfig.cmake` that was present in the build directory. Due to CMP0024 (above), this would produce an error, and the build directory would need to be cleaned to produce a usable configuration.
> cmake config guard for submodule mode

- doc/sphinx/src/building.rst
I have been bit multiple times by the `cmake` package registry pulling out a globally installed version of `ports-of-call` rather than the in-tree version I would like to use. Here I just add some documentation for `ports-of-call` explaining how to handle this issue in downstream codes.
> package registry docs

- spack-repo/packages/ports-of-call/package.py
The current CMake setup doesn't do anything with it.
Should be readded in case CMake is extended to build the documentation and install it.
Closes #18
> spack: Remove +doc variant and dependencies

- CMakeLists.txt
- README.md
- doc/sphinx/src/developing.rst
- doc/sphinx/src/using.rst
- ports-of-call/portable_errors.hpp
In [the Vinet PR](https://github.com/lanl/singularity-eos/pull/202) by @aematts in singularity-eos some issues with the current error handling in singularity-eos were noted. I believe a performance-portable error handling treatment should be developed and properly lives in `ports-of-call`. I introduce it here. In particular, I define several flavors of macro:
- `PORTABLE_REQUIRE` which is an assert statement with file and line numbers
- `PORTABLE_REQUIRE_THROWS` as above but throws an exception
- `PORTABLE_ABORT` which is a fail statement with file and line numbers, resolves to backend aborts appropriate
- `PORTABLE_THROW` resolves to throwing an exception
- `PORTABLE_THROW_IFEXCEPT` resolves to either an exception or an abort depending on portability strategy
- `PORTABLE_WARN` which is a …
> add portable error handling

- ports-of-call/portable_errors.hpp
If we 'require' something, then the _failed_ condition should trigger the error message, not the success. This small change brings the code in line with the documentation and my understanding of the intent of the `REQUIRE` macros.
- N/A If preparing for a new release, update the version in cmake.
> Change behavior of `require` to match documentation

- ports-of-call/portable_errors.hpp
The `require()` function should usually _not_ return since we would hope the condition is `false`. The `[[noreturn]]` decorator applied to a returning function is undefined behavior. With gcc 10, it looks like the compiler uses `[[noreturn]]` to just give up on keeping track of the stack pointer which leads to a segfault.
> Remove [[noreturn]] from 'require' since it should return under most circumstances

- CMakeLists.txt
- test/CMakeLists.txt
- test/test_portsofcall.cpp
Currently the only test in `ports-of-call` is the install test. This PR does a minimal build configuration for inline tests.
I have included a test from `spiner` that tests `PortableMDArray`, but that is just so there is something to test. It appears there are several tests in `spiner` that should properly be in `ports-of-call`.
New CMake options:
- `-DBUILD_TESTING=[ON/OFF]` for triggering the build of the test exe(s)
- `-DPORTS_OF_CALL_TEST_KOKKOS=[ON/OFF]` for configuring for testing with `Kokkos`
I'm taking a "less-is-more" approach here; if you want to test, you need `Catch2` available - diddo with `Kokkos`. Further, I've deliberately left *out* an option for Kokkos CUDA; If you want that, then install Kokkos with CUDA enabled.
Should the git[hub/lab] CI begin running these tests? Or …
> Add core for build tests

- doc/sphinx/src/using.rst
- ports-of-call/portability.hpp
- test/test_portsofcall.cpp
Adds `portableExecIsHost()` function that returns `true` if the execution space is on host, `false` if on device.
For `PORTABILITY_STRATEGY_KOKKOS`, compares `Kokkos::DefaultExecutionSpace` to `Kokkos::HostSpace::execution_space`. This can differentiate between `openmp` and `cuda`, for instance
For the explicit `PORTABILITY_STRATEGY_*`, just return `true` or `false` as expected.
This maybe useful e.g. https://github.com/lanl/spiner/pull/64
> Draft: Add portable query for exec space

- ports-of-call/portability.hpp
`parallelReduce` didn't support 1D or 2D. This PR adds those overloads.
Fixes #14
> Add 1D and 2D parallel reduces

- ports-of-call/portability.hpp
Remove the `inline` keyword from `EXECUTION_IS_HOST` var; `icpc` doesn't like this
> removed inline, icpc complains

- ports-of-call/portability.hpp
- ports-of-call/portable_errors.hpp
This adds an internal print function used by portable errors machinery that stubs out printf on hip where printf doesn't exist.
@Yurlungur @mauneyc-LANL @rbberger @chadmeyer
> First cut at adding printf, help builds.

- ports-of-call/portable_errors.hpp
Quick fix to what appears to be a bug where `condition` was twice in the wrapper for `require()`. This affects the string stream implementation of `PORTABLE_REQUIRE`.
Fixes #43 
- N/A If preparing for a new release, update the version in cmake.
> Change 'condition' to 'condition_bool'

- .github/workflows/tests-minimal.yml
- spack-repo/packages/ports-of-call/package.py
I just noticed that the tests in ports-of-call aren't run on either re-git or github. This at least adds them to the github CI. I also add a test variant and catch2 v3 dependency to the spackage.
> add CI tests and add catch v3 to spackage

- doc/sphinx/src/using.rst
- ports-of-call/array.hpp
- test/CMakeLists.txt
- test/test_array.cpp
An implementation of `std::array` that works on both the CPU and the GPU.
> Transfer array from Singe

- CMakeLists.txt
- spack-repo/packages/ports-of-call/package.py
- test/CMakeLists.txt
Ports of call doesn't set the portability strategy in cmake. Must be set downstream. Here we fix the tests so it is set for testing purposes.
> move target logic into test cmakelist

- .gitlab-ci.yml
- .gitlab/build_and_test.cmake
- .gitlab/build_and_test.sh
- .gitlab/common.yml
- spack-repo/packages/ports-of-call/package.py
> Add ATS4 CI

- CMakeLists.txt
- cmake/config_summary.cmake
A recent addition to Singe.  Jonah said Ports-of-Call might find it useful, so putting together a demo so y'all can see if you like it or not.
@Yurlungur @dholladay00 @cmauney
> Add config_summary to Ports-of-Call.

- doc/sphinx/src/using.rst
- ports-of-call/static_vector.hpp
- test/CMakeLists.txt
- test/test_static_vector.cpp
- test/test_static_vector_iterator.cpp
- test/test_static_vector_kokkos.cpp
A GPU-capable implementation of static vector.  This is a `std::vector`-like data structure built on top of a `std::array`-like backing store, resulting in something with a compile-time capacity but a run-time size.  It works on both the CPU and the GPU, and can be transferred between the two.
> Transfer static vector from Singe

- doc/sphinx/src/using.rst
- ports-of-call/span.hh
- ports-of-call/span.hpp
- test/CMakeLists.txt
- test/test_span.cpp
A `span` implementation that (in broad terms) follows C++20. See https://en.cppreference.com/w/cpp/container/span for more information on this.
This replaces the PR provided by @BrendanKKrueger (https://github.com/lanl/ports-of-call/pull/47) in giving a more complete `span`.
@jonahm-LANL @dholladay00 
TODO:
> Conformant span

- test/test_span.cpp
To fix #63 
Replaced "in-line" pi calculation with explicit decimal value.
@rbberger @jonahm-LANL
> Fix non-constexpr math function

- .gitlab/common.yml
CI job failures were downgraded to warnings. Revert that change.
> ci: re-enable hard failures

- ports-of-call/portability.hpp
- ports-of-call/portable_errors.hpp
Apparently compilers don't like us using `sprintf` because of the risk of writing arbitrary bits to memory. This switches `portable_errors` to using `snprintf` for error messages.
> Add snprintf. Hide sprintf as fancy snprintf

- CMakeLists.txt
- test/CMakeLists.txt
Header files have been added that the CMake install has not kept track of. This changes the install from a "per-file" to a "directory", so that future headers will also be included.
Install before
```bash
$> cmake --install .
-- Install configuration: ""
-- Installing: <prefix>/lib/cmake/ports-of-call/ports-of-callConfig.cmake
-- Installing: <prefix>/lib/cmake/ports-of-call/ports-of-callConfigVersion.cmake
-- Installing: <prefix>/include/ports-of-call/portability.hpp
-- Installing: <prefix>/include/ports-of-call/portable_arrays.hpp
-- Installing: <prefix>/include/ports-of-call/portable_errors.hpp
-- Installing: <prefix>/lib/cmake/ports-of-call/ports-of-callTargets.cmake
```
With PR:
```bash
$> cmake --install .
-- Install configuration: ""
-- Installing: …
```
> Fix CMake install missing header files

- CMakeLists.txt
- spack-repo/packages/ports-of-call/package.py
These changes are backwards compatible all the way to v0.23. Since Singularity-EOS already has them, we should just bring this library up-to-date. There is more Spack related changes incoming due to the Package API v2 changes, but that will be its own PR.
> Prepare for Spack v1.0.0
