lanl/ports-of-call

- doc/sphinx/src/building.rst
- spack-repo/packages/ports-of-call/package.py
Same as #5 but with updated docs.
> Sync with spack upstream

- .github/PULL_REQUEST_TEMPLATE.md
> Add reminder about cmake version in PR checklist

- CMakeLists.txt
Bumping cmake version number. @mauneyc-LANL is this the sequence:
- 1. Bump cmake version and merge
- 2. tag commit from (1.) to correct version
- 3. update spackage in new commit ? 
Something doesn't feel right about this sequence but it looks like the spackage can't be updated until it has a commit hash for the tag.
> Updating ports-of-call version in cmake lists.

- spack-repo/packages/ports-of-call/package.py
> spack: add 1.3.0 release

- spack-repo/packages/ports-of-call/package.py
Sync spackage from https://github.com/spack/spack/pull/35151
These changes keep the spackage functional to also allow installing older versions.
> Draft: Sync spack package

- CMakeLists.txt
- spack-repo/packages/ports-of-call/package.py
Update spack repo and cmake to newest release. 
At a later date, this spackage needs to be migrated upstream.
> update version and spackage

- CMakeLists.txt
> update cmake for release

- CMakeLists.txt
@Yurlungur @rbberger creating a release version from the printf stuff.
> Bump version number in cmake.

- spack-repo/packages/ports-of-call/package.py
> spack: add 1.6.0 release

- CMakeLists.txt
What it says on the can. It's finally time @mauneyc-LANL
> Enable C++17

- .clang-format
- CMakeLists.txt
- cmake/Format.cmake
- doc/sphinx/src/developing.rst
- ports-of-call/portability.hpp
- ports-of-call/portable_arrays.hpp
- ports-of-call/portable_errors.hpp
- script/format.sh
- test/test_portsofcall.cpp
It looks like we don't have the formatting automation we do in `singularity-eos` and `spiner`. I port it over here and also port over the relevant parts of the development guidelines from `singularity-eos`.
> Add automation to formatting and extend development docs

- test/test_array.cpp
Fix a typo that somehow slipped in.
> Should be == instead of =.

- test/test_array.cpp
What it says on the can. Probably this bug was hidden by #55
> Fix array test with kokkos backend

- spack-repo/packages/ports-of-call/package.py
> spack: add missing test dependency

- .gitlab-ci.yml
- .gitlab/build_and_test.sh
> ci: add some test builds

- .gitlab-ci.yml
> Add Venado testing

- doc/sphinx/src/using.rst
- ports-of-call/robust_utils.hpp
> add robust utils header

- .gitlab/common.yml
- CMakeLists.txt
- spack-repo/packages/ports-of-call/package.py
- updates CI configuration
- add missing 1.7.0 version bump in CMakeLists.txt
- add 1.7.0 to Spack package
> CI Updates

- doc/sphinx/src/using.rst
- ports-of-call/portable_arrays.hpp
Add the bracket operator to `PortableMDArray` as suggested by @mauneyc-LANL . This is a bridge contribution in support of #39 . Down the line, we may deprecate the 1D punned `operator()`.
> add bracket operator

- .github/workflows/formatting.yml
- doc/sphinx/src/using.rst
- ports-of-call/math_utils.hpp
- ports-of-call/portability.hpp
- test/test_portability.cpp
> Add PORTABLE_FENCE

- .github/workflows/formatting.yml
- cmake/Format.cmake
- doc/sphinx/src/developing.rst
- ports-of-call/portability.hpp
- script/format.sh
- test/test_main.cpp
- test/test_portability.cpp
- test/test_span.cpp
Again, just doing this to make formatting easier. Time to move on from super outdated clang-format-12.
> update clang format to 19 and perform format sweep
